language: objective-c
script: ant -f macosx/build.xml dmg
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
  - brew update
  - brew install autoconf automake nasm libtool
