language: java

os:
  - linux
  - osx

jdk:
  -
  - oraclejdk8
  - openjdk6

matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
      - autoconf
      - javahelp2
      - tidy
      - liblcms2-dev
      - libtiff4-dev
      - openjdk-6-jdk

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc@7 libtiff little-cms2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then alias jdk_switcher=':' ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ant -f linux/build.xml; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ant -f macosx/build.xml; fi

